#!/usr/bin/env bash
# build.sh — full headless build: compile shaders → publish .NET → package APK
# Requirements: dotnet 8 SDK, Android SDK (ANDROID_HOME), glslc (shaderc)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="$ROOT/src"
OUT="$ROOT/Build"
SHADER_IN="$ROOT/shaders"
SHADER_OUT="$SRC/Resources/shaders"   # embedded as resources

mkdir -p "$OUT" "$SHADER_OUT"

# ── 1. Compile GLSL shaders to SPIR-V ─────────────────────────────────────────
echo "=== Compiling shaders ==="
GLSLC=$(command -v glslc || echo "")
if [[ -z "$GLSLC" ]]; then
  echo "  glslc not found — trying shaderc in Android SDK NDK..."
  NDK="${ANDROID_HOME}/ndk"
  GLSLC=$(find "$NDK" -name glslc -type f 2>/dev/null | head -1)
fi

if [[ -z "$GLSLC" ]]; then
  echo "  ERROR: glslc not found. Install: apt-get install glslc"
  echo "         or set ANDROID_HOME to the Android SDK with NDK."
  exit 1
fi

for shader in "$SHADER_IN"/*.vert "$SHADER_IN"/*.frag; do
  name=$(basename "$shader")
  out="$SHADER_OUT/${name}.spv"
  "$GLSLC" "$shader" -o "$out" -O
  echo "  ✓ $name → $(basename "$out")"
done

# Embed SPIR-V as C# byte arrays so no file I/O is needed on the device
GEN="$SRC/Rendering/ShaderBytecode.g.cs"
echo "// <auto-generated — do not edit; run build.sh to regenerate>" > "$GEN"
echo "namespace SLQuest.Rendering {" >> "$GEN"
echo "  internal static class ShaderBytecode {" >> "$GEN"
for spv in "$SHADER_OUT"/*.spv; do
  varname=$(basename "$spv" .spv | tr '.' '_')
  hex=$(xxd -i < "$spv" | tr -d ' \n' | sed 's/,$//')
  echo "    public static readonly byte[] ${varname} = new byte[]{ ${hex} };" >> "$GEN"
done
echo "  }" >> "$GEN"
echo "}" >> "$GEN"
echo "  ✓ Generated ShaderBytecode.g.cs"

# ── 2. Fetch NuGet dependencies if needed ─────────────────────────────────────
if [[ ! -f "$ROOT/unity/Assets/Plugins/LibreMetaverse/LibreMetaverse.dll" ]]; then
  echo "=== Fetching NuGet packages ==="
  python3 "$ROOT/tools/fetch_packages.py"
fi

# ── 3. Restore .NET packages ───────────────────────────────────────────────────
echo "=== Restoring packages ==="
dotnet restore "$SRC/SLQuest.csproj"

# ── 4. Publish .NET for Android ARM64 ─────────────────────────────────────────
echo "=== Publishing .NET ==="
dotnet publish "$SRC/SLQuest.csproj" \
  -f net8.0-android \
  -r android-arm64 \
  -c Release \
  -o "$OUT/dotnet" \
  /p:AndroidGenerateJavaStubs=false

# The publish step produces Build/dotnet/com.slquest.viewer-Signed.apk
# if ANDROID_HOME is set and a keystore is available, or an unsigned APK otherwise.

APK=$(find "$OUT" -name "*.apk" | head -1)
if [[ -n "$APK" ]]; then
  echo ""
  echo "✅ APK: $APK"
  echo ""
  echo "Deploy:"
  echo "  adb install -r \"$APK\""
  echo "  adb shell monkey -p com.slquest.viewer 1"
else
  echo ""
  echo "✅ Build complete. APK not found in $OUT — check dotnet publish output."
fi
